# Generated by Django 2.2.12 on 2020-07-15 21:23

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.CharField(default=user.models.default_info, max_length=100, verbose_name='简介'),
        ),
    ]
