# Generated by Django 2.2.12 on 2020-07-16 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200716_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='生日'),
        ),
    ]
